# Site settings
title: Edgaras Malcevas
twitter_username: #
name: Edgaras Malcevas

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/edgaras-malcevas-a17b35a9/
 - title: Portfolio
   url: ./portfolio.html

#Any buzzword skills you want to include
skills:
 - PHP
 - Yii2
 - MySQL
 - JavaScript
 - jQuery
 - Angular 2/4
 - Knockout
 - Rest
 - Css/scss
 - Prestashop
 - WordPress
 - Linux


#Work experience is required
roles:
 - title: Front-End programmer
   start: 2018
   end: Ongoing
   employer: Singletonas, UAB
   description: Working with "Angular 4" framework as Front-End developer.
 - title: Full-Stack programmer
   start: 2017
   end: 2018
   employer: ITPC, UAB
   description: Full stack jobs. Mostly working with Yii2 (php) framework, also with "Prestashop".
 - title: Full-Stack/Prestashop programmer
   start: 2016
   end: 2017
   employer: Baltic Home, UAB
   description: Developing new comercial products, old projects maitence, various modules development/maitence.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2012-2015
   subject: Computer Network Administration
   school: Kauno Kolegija - University of Applied Sciences

#This section is optional (as is the image link below)
extraCourses:
   courses:
    - title: Prestashop/web programming basics
      date: 2015-2016

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/learning-neural-networks
# - robhinds/akka-http-rest-api-sample
# - robhinds/twitter-sentiment-analysis
# - robhinds/spring-reactor-twitter
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/food2vec
# - robhinds/SpringMongoIntegrationExample
# - robhinds/SpringNeo4JWebApp
# - robhinds/AndroidChuckQuiz
# - robhinds/AndroidRssReader


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  TODO
#theme: jekyll-theme-cayman