# Site settings
title: Edgaras Malcevas
twitter_username: #
name: Edgaras Malcevas

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/edgaras-malcevas-a17b35a9/
 - title: Portfolio
   url: ./portfolio.html
 - title: Write me an email
   url: mailto:edgarasdarbo@gmail.com

#Any buzzword skills you want to include
skills:
 - PHP
 - Yii2
 - MySQL
 - PostgreSQL
 - MS SQL
 - Oracle
 - DB2
 - JAVA 8
 - JavaScript
 - jQuery
 - Angular 2+
 - Knockout
 - Rest
 - GIT
 - Bootstrap
 - Css/scss
 - Prestashop
 - WordPress
 - Linux
 - IBM MQ
 - TIBCO EMS
 


#Work experience is required
roles:
 - title: Full-Stack programmer
   start: 2017
   end: Ongoing
   employer: Singletonas, UAB
   description: Working with "Angular 2+" framework, JAVA 8, IBM MQ, TIBCO EMS. Using various databases (MySQL, PostgreSQL, Oracle, DB2, MS SQL).
 - title: Full-Stack programmer
   start: 2016
   end: 2017
   employer: ITPC, UAB
   description: Full stack jobs. Mostly working with Yii2 (php) framework, also with "Prestashop".
 - title: Full-Stack/Prestashop programmer
   start: 2015
   end: 2016
   employer: Baltic Home, UAB
   description: Developing new comercial products, old projects maintenance, various modules development/maintenance.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2012-2015
   subject: Computer Network Administration
   school: Kauno Kolegija - University of Applied Sciences

#This section is optional (as is the image link below)
extraCourses:
   courses:
    - title: Prestashop/web programming basics
      date: 2015-2016

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/learning-neural-networks
# - robhinds/akka-http-rest-api-sample
# - robhinds/twitter-sentiment-analysis
# - robhinds/spring-reactor-twitter
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/food2vec
# - robhinds/SpringMongoIntegrationExample
# - robhinds/SpringNeo4JWebApp
# - robhinds/AndroidChuckQuiz
# - robhinds/AndroidRssReader


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <b>Languages:</b> English, Russian<br>
  <b>Car licence:</b> B kategory<br>
  <b>Birth date:</b> 08/03/1990<br><br>
  <b>More about me: </b><br>
  In university I was very active and made some projects, like robot hit detection system (with gsm module).
  Also I participated in conference with "quiz" program developed with "Perl".
  Additionally I won "STT" (Special Investigation Bureau) contest by making animated banner (using Flash 8.0).
  <br>
  I am self-motivated and eager to learn new things. <br><br>
  <b>Hobbies:</b><ul>
  <li>
  I love to work with Raspberry pi <img src="../img/raspberry-pi-logo.png">.
  </li>
  <li>
  All kind of health activities.
  </li>
  <li>
  In free time I like to read about new technologies/their working principles, programming trends.
  </li>
  </ul> <br>
#theme: jekyll-theme-cayman